from rest_framework.serializers import ModelSerializer
from . import models


class FlatDataSerializer(ModelSerializer):

    class Meta:
        model = models.FlatData
        fields = (
            'id',
            'sys_id',
            'org_id',
            'biz_id',
            'field_01',
            'field_02',
            'field_03',
            'field_04',
            'field_05',
            'field_06',
            'field_07',
            'field_08',
            'field_09',
            'field_10',
            'field_11',
            'field_12',
            'field_13',
            'field_14',
            'field_15',
            'field_16',
            'field_17',
            'field_18',
            'field_19',
            'field_20',
            'field_21',
            'field_22',
            'field_23',
            'field_24',
            'field_25',
            'field_26',
            'field_27',
            'field_28',
            'field_29',
            'field_30',
            'int_01',
            'int_02',
            'int_03',
            'int_04',
            'int_05',
            'int_06',
            'int_07',
            'int_08',
            'int_09',
            'int_10',
            'float_01',
            'float_02',
            'float_03',
            'float_04',
            'float_05',
            'float_06',
            'float_07',
            'float_08',
            'float_09',
            'float_10',
        )


class FlatTemplateSerializer(ModelSerializer):

    class Meta:
        model = models.FlatTemplate
        fields = (
            'id',
            'sys_id',
            'org_id',
            'biz_id',
            'template_id',
            'template_name',
            'create_time',
            'update_time',
            'field_01',
            'field_02',
            'field_03',
            'field_04',
            'field_05',
            'field_06',
            'field_07',
            'field_08',
            'field_09',
            'field_10',
            'field_11',
            'field_12',
            'field_13',
            'field_14',
            'field_15',
            'field_16',
            'field_17',
            'field_18',
            'field_19',
            'field_20',
            'field_21',
            'field_22',
            'field_23',
            'field_24',
            'field_25',
            'field_26',
            'field_27',
            'field_28',
            'field_29',
            'field_30',
        )


class FlatConfigSerializer(ModelSerializer):

    class Meta:
        model = models.FlatConfig
        fields = (
            'id',
            'sys_id',
            'org_id',
            'biz_id',
            'field_01',
            'field_02',
            'field_03',
            'field_04',
            'field_05',
            'field_06',
            'field_07',
            'field_08',
            'field_09',
            'field_10',
            'field_11',
            'field_12',
            'field_13',
            'field_14',
            'field_15',
            'field_16',
            'field_17',
            'field_18',
            'field_19',
            'field_20',
            'field_21',
            'field_22',
            'field_23',
            'field_24',
            'field_25',
            'field_26',
            'field_27',
            'field_28',
            'field_29',
            'field_30',
            'field_type_01',
            'field_type_02',
            'field_type_03',
            'field_type_04',
            'field_type_05',
            'field_type_06',
            'field_type_07',
            'field_type_08',
            'field_type_09',
            'field_type_10',
            'field_type_11',
            'field_type_12',
            'field_type_13',
            'field_type_14',
            'field_type_15',
            'field_type_16',
            'field_type_17',
            'field_type_18',
            'field_type_19',
            'field_type_20',
            'field_type_21',
            'field_type_22',
            'field_type_23',
            'field_type_24',
            'field_type_25',
            'field_type_26',
            'field_type_27',
            'field_type_28',
            'field_type_29',
            'field_type_30',
        )


class FlatDataReportConfSerializer(ModelSerializer):

    class Meta:
        model = models.FlatDataReportConf
        fields = (
            'id',
            'sys_id',
            'org_id',
            'biz_id',
            'report_id',
            'report_name',
            'flat_config',
            'arguments',
            'data_struct',
            'charts_struct',
        )
